apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisord-config
data:

  # file-like keys
  supervisord.conf: |
    [supervisorctl]

    [supervisord]
    nodaemon=true
    logfile=/var/log/supervisord.log

    [program:jupyter_notebook]
    command=jupyter-notebook --allow-root
